### ISSUE TITLE
520 error causes crash

### ISSUE THREAD

**Issue by MMMUFFINS** [MMMUFFINS/discord-clear-channel-bot#3]
Not exactly sure what caused this, as the only messages it should have seen are the following:

```
[Fellow Unicum]: !stats ichimuta eu
[Fellow Unicum]: !delet
```

No response from the bot to the 2nd command (user doesn't have manage message permissions)

Console log of error:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (520)
    at ClientRequest._req.on (/usr/src/app/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-clear-channel-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-clear-channel-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-06T09_03_02_679Z-debug.log
```

I didn't get the debug file sadly, I'll try to remember next time (ran ./update without thinking)

**Comment by Loanontheroad** [comment]
Happens to me too with my bot, done randomly. I think it's something related with discord services, they're experiencing API problems (I rode that somewhere, not confirmed) D:
